sudo: false
language: node_js
node_js:
  - '8'
addons:
  apt:
    packages:
      - sshpass
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
  - npminstall codecov && codecov
after_script:
  - sshpass -p $SSHPASSWORD ssh $SSHUSER@$SERVERHOST
  - ls
