sudo: false
language: node_js
node_js:
  - '8'
addons:
  apt:
    packages:
      - sshpass
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
  - npminstall codecov && codecov
after_script:
  - tar -zcvf wxServer.tar.gz --exclude=node_modules **/*.*
  - sshpass -p $SSHPASSWORD scp wxServer.tar.gz $SSHUSER@$SERVERHOST -o stricthostkeychecking=no
  - sshpass -p $SSHPASSWORD ssh $SSHUSER@$SERVERHOST -o StrictHostKeyChecking=no "ls && exit"
