sudo: false
test:
  language: node_js
  addons:
    apt:
      packages:
        - sshpass
  node_js:
    - '8'
  install:
    - npm i npminstall && npminstall
  script:
    - npm run ci
  after_script:
    - npminstall codecov && codecov
  on:
    branch: develop
    branch: master
deploy:
  script:
    - node test.js



